version: "3.9"  # optional since v1.27.0
services:
  off-risk-server:
    ports:
      - "8123:80"
    volumes:
      - C:\Users\Owner\OneDrive - post.bgu.ac.il\Crispr\mnt\gogenome\off-tov\databases\:/databases
#    image: almaliahbgu/off_risk:off-risk-server
#    image: off-risk-server
    build:
      context: ../

  off-risk-ui:
    ports:
     - "8501:8501"
    build:
      context: ../../OffRisk-ui/
#    image: almaliahbgu/off_risk:off-risk-ui
#    image: off-risk-ui
networks:
  off-risk-net:
    external: true
# default:
#  external:
#    name: off-risk-net