version: "3.9"  # optional since v1.27.0
services:
  off-risk-server:
    ports:
      - "8123:80"
    volumes:
      - <path_to_database_folder>/databases:/databases
    image: almaliahbgu/off_risk:off-risk-server

  off-risk-ui:
    ports:
     - "8501:8501"
    image: almaliahbgu/off_risk:off-risk-ui
networks:
 default:
   external:
    name: OffRisk-net