version: "3.9"  # optional since v1.27.0
services:
  off-risk-server:
    ports:
      - "8123:80"
    volumes:
      - <path_to_database_folder>/databases:/databases
    image: talmalulbgu/off-risk-server:latest

  off-risk-ui:
    ports:
     - "8501:8501"
    image: talmalulbgu/off-risk-ui:latest
networks:
  off-risk-net:
    external: true

# default:
#  external:
#    name: off-risk-net