# Comment
yaml-version: 1.0
genomes:
  human: /databases/genome/hg38.fa
  mouse: /gogenome/off-tov/databases/genome/hg38.fa
  hamster: /gogenome/off-tov/databases/genome/hg38.fa
  fly: /gogenome/off-tov/databases/genome/hg38.fa
  soybean: /gogenome/off-tov/databases/genome/hg38.fa
  tomato: /gogenome/off-tov/databases/genome/hg38.fa
databases:
  base_path: /gogenome/off-tov/databases
  gencode:
    human:
      path: GENCODE/gencode.v42.chr_patch_hapl_scaff.annotation_sort.gff3
      columns:
        - off_target_id
        - ot_chromosome
        - ot_start
        - ot_end
        - gene_ensembl_id
        - gene_symbol
        - segment
        - start
        - end
        - strand
        - gene_type
        - transcript_ensembl_id
        - transcript_type
        - transcript_symbol
        - protein_id
        - exon_number
        - exon_id
      select_attributes:
        - original_name: gene_ensembl_id
          return_name: gene_ensembl_id
        - original_name: gene_symbol
          return_name: gene_symbol
        - original_name: segment
          return_name: segment
  mirgene:
    human:
      path: MirGeneDB/mirgene.bed
      columns:
        - off_target_id
        - ot_chromosome
        - ot_start
        - ot_end
        - mir_symbol
        - start
        - end
        - strand
      select_attributes:
        - original_name: mir_gene
          return_name: mir_gene
  remapepd:
    human:
      path: ReMap_EPD/remap_epd.bed
      columns:
        - off_target_id
        - ot_chromosome
        - ot_start
        - ot_end
        - gene_ensembl_id
        - epd_gene_symbol
        - start
        - end
        - strand
        - remap
        - epd_coding
      select_attributes:
        - original_name: remap_epd_gene_ensembl_id
          return_name: remap_epd_gene_ensembl_id
  enhanceratlas:
    human:
      path: EnhancerAtlas/enhanceratlas.bed
      columns:
        - off_target_id
        - ot_chromosome
        - ot_start
        - ot_end
        - gene_ensembl_id
        - gene_symbol
        - gene_start
        - enh_start
        - enh_stop
        - enhancer_gene_score
        - tissue
      select_attributes:
        - original_name: enhancer_atlas_gene_ensembl_id
          return_name: enhancer_atlas_gene_ensembl_id
  pfam:
    human:
      path: Pfam_protein_domains/pfam_protein_domains.bed
      columns:
        - off_target_id
        - ot_chromosome
        - ot_start
        - ot_end
        - gene_ensembl_id
        - gene_symbol
        - start
        - end
        - pfam_domain_name
      select_attributes:
        - original_name: pfam_protein_domains
          return_name: pfam_protein_domains
  targetscan:
    human:
      path: TargetScan/targetscan.bed
      columns:
        - off_target_id
        - ot_chromosome
        - ot_start
        - ot_end
        - gene_ensembl_id
        - gene_symbol
        - mir_symbol
      select_attributes:
        - original_name: targetscan
          return_name: targetscan
  omim:
    human:
      path: OMIM/omim.csv
      columns:
        - off_target_id
        - gene_ensembl_id
        - gene_symbol
        - omim_id
        - disease_related
        - inheritance_model
      select_attributes:
        - original_name: disease_related
          return_name: disease_related
        - original_name: inheritance_model
          return_name: inheritance_model
  humantf:
    human:
      path: HumanTFDB/human_tf.csv
      columns:
        - off_target_id
        - gene_ensembl_id
        - gene_symbol
        - Family
        - source
      select_attributes:
        - original_name: source
          return_name: HumanTF_source
  protein_atlas:
    human:
      path: ProteinAtlas/protein_atlas.csv
      columns:
      select_attributes:
        - original_name: expression_information
          return_name: expression_information
  rbp:
    human:
      path: RBP/rbp.csv
      columns:
        - off_target_id
        - gene_ensembl_id
        - gene_symbol
        - Essential Genes
        - Splicing regulation
        - Spliceosome
        - RNA modification
        - 3' end processing
        - rRNA processing
        - Ribosome & basic translation
        - RNA stability & decay
        - microRNA processing
        - RNA localization
        - RNA export
        - Translation regulation
        - tRNA regulation
        - mitochondrial RNA regulation
        - Viral RNA regulation
        - snoRNA / snRNA / telomerase
        - P-body / stress granules
        - Exon Junction Complex
  cosmic:
    human:
      path: COSMIC/cosmic.csv
      columns:
        - off_target_id
        - gene_ensembl_id
        - gene_symbol
        - Name
        - Somatic
        - Germline
        - Tumour Types(Somatic)
        - Tumour Types(Germline)
        - Molecular Genetics
        - Role in Cancer
      select_attributes:
        - original_name: cancer_related
          return_name: cancer_related
  OtherOrganisms:
    mouse:
      path: OtherOrganisms/GCF_000001635.26_GRCm38.p6_genomic_chr_names.filtered.removed_sgement_match.added.sorted.gff
      columns:
        - chromosome
        - source
        - segment
        - start
        - end
        - score
        - strand
        - frame
        - attributes
        - ot_chromosome
        - ot_start
        - of_end
        - off_target_id
        - ot_score
        - ot_strand
        - ot_attributes
        - ot_id
        - ot_sequence
      select_attributes:
        - original_name: segment
          return_name: segment
        - original_name: gene
          return_name: gene_symbol
    hamster:
      path: OtherOrganisms/GCF_003668045.3_CriGri-PICRH-1.0_genomic_chr_names.filtered.removed_sgement_match.added.sorted.gff
      columns:
        - chromosome
        - source
        - segment
        - start
        - end
        - score
        - strand
        - frame
        - attributes
        - ot_chromosome
        - ot_start
        - of_end
        - off_target_id
        - ot_score
        - ot_strand
        - ot_attributes
        - ot_id
        - ot_sequence
      select_attributes:
        - original_name: segment
          return_name: segment
        - original_name: gene
          return_name: gene_symbol
    fly:
      path: OtherOrganisms/GCF_905115235.1_iHerIll2.2.curated.20191125_genomic_chr_names.filtered.removed_sgement_match.added.sorted.gff
      columns:
        - chromosome
        - source
        - segment
        - start
        - end
        - score
        - strand
        - frame
        - attributes
        - ot_chromosome
        - ot_start
        - of_end
        - off_target_id
        - ot_score
        - ot_strand
        - ot_attributes
        - ot_id
        - ot_sequence
      select_attributes:
        - original_name: segment
          return_name: segment
        - original_name: gene
          return_name: gene_symbol
    soybean:
      path: OtherOrganisms/GCF_000004515.5_Glycine_max_v2.1_genomic_for_CRISPRIL.filtered.removed_sgement_match.added.sorted.gff
      columns:
        - chromosome
        - source
        - segment
        - start
        - end
        - score
        - strand
        - frame
        - attributes
        - ot_chromosome
        - ot_start
        - of_end
        - off_target_id
        - ot_score
        - ot_strand
        - ot_attributes
        - ot_id
        - ot_sequence
      select_attributes:
        - original_name: segment
          return_name: segment
        - original_name: gene
          return_name: gene_symbol
    tomato:
      path: OtherOrganisms/M82_MAS2.0_gene_models.removed_sgement_match.added.sorted.gff
      columns:
        - chromosome
        - source
        - segment
        - start
        - end
        - score
        - strand
        - frame
        - attributes
        - ot_chromosome
        - ot_start
        - of_end
        - off_target_id
        - ot_score
        - ot_strand
        - ot_attributes
        - ot_id
        - ot_sequence
      select_attributes:
        - original_name: segment
          return_name: segment
        - original_name: gene
          return_name: gene_symbol
    prawn:
      path: OtherOrganisms/MR_Maker_annotations_edited.removed_sgement_match.added.sorted.gff
      columns:
        - chromosome
        - source
        - segment
        - start
        - end
        - score
        - strand
        - frame
        - attributes
        - ot_chromosome
        - ot_start
        - of_end
        - off_target_id
        - ot_score
        - ot_strand
        - ot_attributes
        - ot_id
        - ot_sequence
      select_attributes:
        - original_name: segment
          return_name: segment
        - original_name: gene
          return_name: gene_symbol
off_target_result_columns:
  - off_target_id
  - chromosome
  - start
  - end
  - strand
  - score
  - attributes
  - id
  - sequence
  - gene_ensembl_id
  - gene_symbol
  - segment
  - mir_gene
  - pfam_protein_domains
  - targetscan
  - disease_related
  - inheritance_model
  - HumanTF_source
  - expression_information
  - rbp_gene_ensembl_id
  - cancer_related
  - remap_epd_gene_ensembl_id
  - remap_epd_disease_related
  - remap_epd_inheritance_model
  - remap_epd_cancer_related
  - enhancer_atlas_gene_ensembl_id
  - enhancer_atlas_disease_related
  - enhancer_atlas_inheritance_model
  - enhancer_atlas_cancer_related
  - risk_score
log:
  log_path: ../log/run.log
cas_offinder:
  default_genome: human
  device: C